### ISSUE TITLE
cffi::*libffi-type-pointer* is full of dead pointers

### ISSUE THREAD

**Issue by sionescu** [cffi/cffi#264] opened 2021-12-25 01:43 UTC
I am working on a program that uses cffi and libffi to call into a C library.  I found that when I used CCL's save-application function, my program would encounter an error condition in `CFFI:PREPARE-FUNCTION`.  It says "The value #<A Dead Mac Pointer> is not of the expected type `CCL:MACPTR`.".  If I simply ran ccl and --load'ed my source, then it ran without issue.  After a little investigation, I found that `CFFI::*LIBFFI-TYPE-POINTER*`'s values were all dead pointers.

This makes some sense.  The hash table's values are foreign pointers, and the hash table is populated when I load cffi-libffi.  Additionally, foreign pointers are invalidated in dumped images.  So, when I run my program from the generated executable, all of the foreign pointers are rightfully dead.

It seems like CFFI should empty the hash table (and then repopulate it) when a dumped image is loaded back in.

Launchpad Details: [#LP1484306](https://bugs.launchpad.net/bugs/1484306) Brad Jensen - 2015-08-13 00:06:37 +0000

**Comment by sionescu** [comment] 2021-12-25 01:43
This still seems to be happening.. The code changed but the problem seems to have persisted.. 

Launchpad Details: [#LPC](https://bugs.launchpad.net/cffi/+bug/1484306/comments/1) Ekaterina Vaartis - 2019-06-04 20:53:29 +0000

**Comment by attila-lendvai** [comment] 2021-12-25 18:51
i have wiped out the type cache (it wasn't thread safe) in https://github.com/cffi/cffi/commit/26f11a2bfe6c00e82fc5853173cb2303bb56e1df

and the other issue is a duplicate of https://github.com/cffi/cffi/issues/301

**Closed by attila-lendvai** 2021-12-25 18:51 UTC
