### ISSUE TITLE
Errors in libffi-types.lisp on aarch64

### ISSUE THREAD

**Issue by sionescu** [cffi/cffi#294] opened 2021-12-25 02:15 UTC
libffi-types.lisp seems in error. Installed the quicklisp version. The FFI_DEFAULT_ABI portion has: 

#-(or freebsd windows)
(cenum abi
 ((:default-abi "FFI_DEFAULT_ABI"))
 #-x86-64
 ((:sysv "FFI_SYSV"))
 ((:unix64 "FFI_UNIX64")))

On SBCL 2.0.11 / Linux / aarch64 this is picked up as applying the last :unix64 part. 

The FFI_DEFAULT_ABI on Linux / aarch64 is FFI_SYSV. 

Commenting out the :unix64 and closing up the sexp as so: 

#-(or freebsd windows)
(cenum abi
 ((:default-abi "FFI_DEFAULT_ABI"))
 #-x86-64
 ((:sysv "FFI_SYSV")))
;; ((:unix64 "FFI_UNIX64")))

This allows things to build correctly. I used the result to compile MAGICL, and ran all tests successfully.

Launchpad Details: [#LP1908964](https://bugs.launchpad.net/bugs/1908964) Michael Graffam - 2020-12-22 02:46:54 +0000

**Comment by attila-lendvai** [comment] 2021-12-25 21:12
duplicate of https://github.com/cffi/cffi/issues/297

**Closed by attila-lendvai** 2021-12-25 21:12 UTC
